# Generated by Django 5.0.3 on 2024-07-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='owner',
        ),
    ]
