# Generated by Django 5.0.3 on 2024-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0003_alter_sale_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
