# Generated by Django 5.0.7 on 2024-09-11 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0005_sales_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_services',
            name='datePaid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
